### ISSUE TITLE
Packaging issues

### ISSUE THREAD

**Issue by VorpalBlade** [keirf/disk-utilities#118]
I was looking at packaging this as a -git package for Arch Linux AUR (as there are no releases that I can tell for this repo). I ran into two issues:

1) For creating a distro package, being able to install to a separate destination prefix is needed.  This is generally done by `make DESTDIR=/tmp/some-path install`. This would then install to `$(DESTDIR)/$(PREFIX)/...`. This package does not seem to support that, so I hacked around it by setting `PREFIX=$DESTDIR/usr`, but I don't know if that could break other things, such as embedded paths, rpaths etc.
2) It seems this package ignores/overwrites LDFLAGS set by the distribution. Arch Linux sets `LDFLAGS=-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now` but that doesn't seem to take effect, generating a packaging warning:
```
 disk-utilities-git W: ELF file ('usr/bin/disk-analyse') lacks FULL RELRO, check LDFLAGS.
```
I believe the fix is as simple as adding LDFLAGS to the disk-analyse target.

**Comment by keirf** [comment]
Let me know or make a PR for any further packaging issues.
