### ISSUE TITLE
Support "Seek and Destroy" disk format

### ISSUE THREAD

**Issue by renaudguerin** [keirf/disk-utilities#172]
I'm trying to convert SCP dumps of [Seek and Destroy](https://hol.abime.net/1862) to IPF using `disk-analyse`, but their format isn't properly detected using `probe_amiga`.

I'd attach the compressed SCPs here but the archive is just over the 25MB limit, please let me know where you want them uploaded.

**Comment by keirf** [comment]
Upload them to a cloud drive or open server (eg "the zone" on EAB)

**Comment by renaudguerin** [comment]
[Here](https://www.dropbox.com/s/ldqvg68dswg7l15/seekdestroy.7z?dl=0) it is (for a limited time).

**Comment by keirf** [comment]
Copied to my Drive: https://drive.google.com/file/d/1FBh_A6FQe-xMEcL_3sm_SnMIwZfkLi7r/view?usp=share_link

**Comment by keirf** [comment]
Someone will pick this up at some point. No time guarantees.

**Comment by kkrellwitz** [comment]
@renaudguerin I will add the format definition for it as the disk format is already supported.  Just use the Skidmarks format for now to create the IPFs.

**Comment by renaudguerin** [comment]
> @renaudguerin I will add the format definition for it as the disk format is already supported. Just use the Skidmarks format for now to create the IPFs.

Thanks ! Verified working. I made a PR : #175
