### ISSUE TITLE
Error:  libdisk.so.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by m0zzaR** [keirf/disk-utilities#190]
This error occurs when I try to run:
```
disk-analyze image.IMG image.IMG
```

**Comment by keirf** [comment]
libdisk.so.0 needs to be on your library search path. It may have got installed to an incorrect location. You will need to 
```
export LD_LIBRARY_PATH=/use/local/lib
```
Or similar, to add the path to the library to the dynamic linker's library search paths.
