### ISSUE TITLE
Possible bug in adfbb.c in recognizing kick 2.0 boot blocks

### ISSUE THREAD

**Issue by ZorroDJ** [keirf/disk-utilities#210]
There's an error in printf IMHO:

    if (!compare_bb(bb, kick13_bootable, sizeof(kick13_bootable)))
        printf("Kickstart 1.3 bootblock\n");
    else if (!compare_bb(bb, kick20_bootable, sizeof(kick20_bootable)))
        printf("Kickstart 1.3 bootblock\n");
    else if (!test_lamer(bb))

otherwise it alwasy write that it's a kick 1.3 bootblock.
Thanks a lot for your work, amiga wizard!

**Comment by keirf** [comment]
Thanks! Fixed now. :)
