### ISSUE TITLE
MacOS 14.6.1 compilation fails with error in amiga/okay_protection.c

### ISSUE THREAD

**Issue by 0ddjob** [keirf/disk-utilities#213]
Scratching my head a bit.  Have cloned the repository and tried compiling from the repository root as per instructions, however fails with an error for file /libdisk/format/amiga/okay_protection.c.  

```
gcc -O2 -fno-strict-aliasing -std=gnu99 -Wall -Werror -I../../libdisk/include -MMD -MF amiga/.okay_protection.opic.d  -fPIC -fvisibility=hidden -c -o amiga/okay_protection.opic amiga/okay_protection.c
amiga/okay_protection.c:23:9: error: variable 'counter' set but not used [-Werror,-Wunused-but-set-variable]
    int counter = 0;
        ^
1 error generated.
make[2]: *** [amiga/okay_protection.opic] Error 1
make[1]: *** [all] Error 2
make: *** [all] Error 2
```

When I check the source file I can see that the variable ```counter``` is used inside a while loop:

```
    /* GCR 4us bit time */
    stream_set_density(s, 4000);
    int counter = 0;
    while (stream_next_bit(s) != -1) {
        unsigned int i, count;
        counter++;
```
[disk_utilities_compile_error_19-Aug-2024.txt](https://github.com/user-attachments/files/16655716/disk_utilities_compile_error_19-Aug-2024.txt)

**Comment by kkrellwitz** [comment]
Will look into it tonight .

**Comment by kkrellwitz** [comment]
Looks like I just need to remove the variable counter and the increment
statement.  The variable was used for debugging and forgot to remove it.

**Comment by 0ddjob** [comment]
Ach, sorry - I could've tried that myself! I'm mainly interested in Osborne 1 disk images at the moment so would never have used the Amiga stuff.

I was wondering if the WHILE loop was never triggered, thus the counter variable never actually used ... hence the compile error ... ?

Anyway, tried it now and compiles nicely!  Thanks.

```
    /* GCR 4us bit time */
    stream_set_density(s, 4000);
    while (stream_next_bit(s) != -1) {
        unsigned int i, count;
        if ((uint16_t)s->word != 0xbdef)
            continue;
```

[disk-utilties_compile_OK_20-Aug-2024.txt](https://github.com/user-attachments/files/16666720/disk-utilties_compile_OK_20-Aug-2024.txt)
