### ISSUE TITLE
Mac error on make?

### ISSUE THREAD

**Issue by cheekymonkat** [keirf/Disk-Utilities#40]
Hi, I've tried your instructions but I get the error on both Yosemite and El Capitan..

iscferret_dfe2.c:113:9: error: taking the absolute value of unsigned type 'unsigned int' has no effect [-Werror,-Wabsolute-value]
    if (abs((index_pos * 5) - MHZ(25)) < (MHZ(25) * DRIVE_SPEED_UNCERTAINTY))
        ^

**Comment by keirf** [comment]
Fixed, thank you.
