### ISSUE TITLE
Max track problems in scp_dump.c

### ISSUE THREAD

**Issue by M-a-r-k** [keirf/Disk-Utilities#43]
In scp_write.c you use a hard-coded maximum tracks number of 168:
```
if ((end_trk >= 168) || (start_trk > end_trk)) {
    warnx("Bad track range (%u-%u)", start_trk, end_trk);
```
That matches the maximum number of cyclinders supported by the SuperCard Pro Windows software, i.e. 84 (0-83). However in scp_dump.c you have
```
#define MAX_TRACKS         166
```
Which limits to 83 tracks (0-82). So MAX_TRACKS should be changed to 168.

Also, related to the -D double-stepping option, you have:
```
while ((ch = getopt_long(argc, argv, sopts, lopts, NULL)) != -1) {
    switch (ch) {
...
    case 'D':
        double_step = 1;
        end_trk = 81;
        break;
```
If the user specifies -e for the last track to dump before -D on the command line, the -e value will be ignored, and the hard-coded value 81 used instead. On the other hand, if -e appears after -D then the user's setting will be respected. To fix that, perhaps make MAX_TRACKS a variable, set to 168 initially and if -D is specified divide it by 2.

**Comment by keirf** [comment]
Thanks, MAX_TRACKS should indeed be 168 as that is the size of the Track-Data-Offsets array in the SCP image file. Also agree the double-step handling could be done better. Should all be fixed now, let me know if not.
