### ISSUE TITLE
SCP: Implement settle delay for reading & writing

### ISSUE THREAD

**Issue by M-a-r-k** [keirf/Disk-Utilities#44]
After you finish stepping heads to the desired track, there should be a larger delay (the settle delay) before you begin reading or writing data. That's typically specified as 15ms or 18ms minimum in drive datasheets.

scp_dump and scp_write don't seem to do that; scp_seek_track() is immediately followed by scp_read_flux() or scp_write_flux().

The SuperCard Pro firmware by default uses a 5ms delay after stepping the heads. (The step-to-zero command has a 15ms delay.)

So I think it would be good to:
 - Allow the user to specify step delay (most 80-track 3.5" drives are documented to work with 3ms, 40-track drives may need 6ms)
 - Use a default settle delay of, say, 20ms (so wait 17ms after stepping if you've set step delay to 3ms). But you could allow the user to specify that too.

In practice, problems caused by the lack of settle delay could be masked for a couple of reasons:
 - The Windows SCP software apparently sets the SCP step delay to 20ms. If the user has previously used the Windows software and not powered down the SCP before using scp_dump/scp_write, it will continue to use that large delay.
 - If you're reading/writing synced to the index pulse, an average of 100ms (half a revolution at 300rpm) will pass until the read/write begins.

**Comment by keirf** [comment]
Thank you, this is all now implemented as you requested.

**Comment by M-a-r-k** [comment]
Many thanks!
