### ISSUE TITLE
disk-analyse: Create IPFs reproducibly?

### ISSUE THREAD

**Issue by M-a-r-k** [keirf/Disk-Utilities#46]
Not sure whether this is possible without modifying the SPS IPF library code, but anyway...

The current date/time is stored in IPF files which disk-analyse creates. So if you create an IPF from the same source file several times, the MD5 hashes of each IPF file differ. Alternatively, if you create an IPF from another original copy of a game, it will always differ from the first one even if both disks are (effectively) identical.

The ability to not store the current date/time would be good. Then the user could easily see whether IPFs they created from their original disks match those created by others. But the IPF format seems to require that a date/time be stored, so perhaps agree on a fixed date to always store there? (1978-01-01 would be somehow appropriate for AmigaDOS...)

Or perhaps someone could write an ipf-compare utility which would compare IPFs ignoring the date fields.

**Comment by keirf** [comment]
Date/time isn't the only way in which an IPF generated from different dumps of the same disk can differ. There is also at least the start-offset of each track from the index mark, which will jitter by a few bits either way across dumps of the very same disk.

An existing fairly safe way to compare images for identical data is to use disk-analyse to convert them to its own DSK format, and use the -i flag to index-align tracks and thus fix their start-offsets:
# disk-analyse -i a.ipf a.dsk
# disk-analyse -i b.ipf b.dsk
# diff a.dsk b.dsk
