### ISSUE TITLE
Feature: FUSE support

### ISSUE THREAD

**Issue by rlake** [keirf/Disk-Utilities#55]
Add a frontend to read/write disk images with FUSE (https://github.com/libfuse/libfuse) for host access.

In turn I suppose this ought to be mountable in UAE as a live HDF.

**Comment by keirf** [comment]
Not sure this makes sense. UAE can already read/write disk images. Disk-Utilities:disk-analyse is a floppy-disk-image transcoder, no clear relation to UAE HDFs.
