### ISSUE TITLE
Support for Herndon HLS copy protection

### ISSUE THREAD

**Issue by KKR775** [keirf/Disk-Utilities#68]
I am trying to create a dump for TV Sports Football, and noticed track 1.0 and 1.1 (so tracks 2 and 3) are longtracks. Even though I tried to add a new entry for that game using the amigados_long_105500 , the game refuses to load because it gets stuck at track 2 trying to decode HLS Herndon.

Can a coder please provide support for that protection in the formats file? I also read on the net that a few games are protected by this, for example, the early King's Quest series.

Thanks

**Comment by keirf** [comment]
Can you supply a dump or give an SPS IPF number which definitely exhibits this protection?

**Comment by KKR775** [comment]
Certainly, here you go. You can also find this file in SPS #0407.

[TVSportsFootball_Disk1.zip](https://github.com/keirf/Disk-Utilities/files/3968342/TVSportsFootball_Disk1.zip)

**Comment by keirf** [comment]
Do you have a raw dump you are trying to convert, or are you simply trying to transcode the IPF to another format (SCP?). I like to work from a dump as well as the IPF if possible.

**Comment by keirf** [comment]
Interestingly I have a few Herndon/HLS titles listed as amigados_long in disk-analyse/formats. I'm pretty sure these are wrong, and were taken from a contributor who got a false match.

**Comment by KKR775** [comment]
[https://drive.google.com/file/d/1MCC5J9MeAbgAqaDvqLwypN__tT5Q1rWB/view?usp=sharing](url)

Here you go, this is the raw dump from my floppy disk which is the same as the SPS 0407 IPF.
Compressed in tar BZ2,

**Comment by keirf** [comment]
Okay see how that works for you.

I'm also interested if you come across any other Herndon HLS titles. I'm not sure they will all have the same protection track format!

**Comment by KKR775** [comment]
Keir,
I just created an IPF from the updated Disk-Utilities and it works like a charm ! Thank you !
I will check other programs as well. I have the originals for Kings Quest I II and III, and I had dumped them on ADF from my RAW files, but I just tried them (I never did before) and they don't work. I will make an IPF from them, but I suspect they won't work either. In that case I will try to use the TVSportsFootball format and report back if this works or not.

**Comment by KKR775** [comment]
Keir,

My Kings Quest dumps are not working, and they seem to all have different format. For example, KQ1 has a track 111000 long, whereas 2 and 3 don't show anything but they still don't work.

Below are the links. Please let me know as soon as you download them so I can remove the link.

Thank you

Kings Quest: [https://drive.google.com/open?id=15BBgFBeLKI2Z4ZmPkRW-Z6qt-lNoOs2k](url)

Kings Quest II: [https://drive.google.com/open?id=1ZghBhAu___xJT4F8Lx7nLp15xaktZyCu](url)

Kings Quest III: [https://drive.google.com/open?id=14AGsJYEPQS5dycmbmLoBQGdUfp7eOiGK](url)

**Comment by keirf** [comment]
Downloaded them, thanks.

**Comment by keirf** [comment]
King's Quest is added: It's a simple longtrack check (~111000 bitcells needed on track 1).
Please test. It may only be on Disk 1, in which case the rest are probably plain amigados.

**Comment by keirf** [comment]
I don't believe your KQ2 or KQ3 disks have any protection. Bear in mind:
1. Neither is bootable, so you need to load Workbench first, or install a valid bootblock.
2. Neither has a startup-sequence, so you need to run "KQ2" or "KQ3" from the CLI/Workbench.

The IPF 0520 (KQ2) similarly has no protection. IPF 0521 (KQ3) has the same Herndon protection as KQ1 (Long Track 1).

If you want me to send you bootable ADFs of your KQ2 and KQ3 I can do that.

**Comment by KKR775** [comment]
I will test when I get home tonight. But a few things to point out:
1. All 3 KQ have only one disk each game.
2. All 3 have no startup-sequence, it seems Sierra had mistakenly omitted to include them. So they are not bootable.
3. If you check the WHDLoad ReadMe files for the installs of those games, they all mention that they are protected with HLS (all 3 games). The install script themselves do create a startup-sequence, otherwise the game won't work.

In any case, I can manually create a startup-sequence for each of those games.

**Comment by KKR775** [comment]
actually, i have linux at work where i installed Disk-Utilities so I will do my checking here. 

Out of curiosity, how do you manage to create ADF out of longtracks? disk-analyze gives me an error saying only AmigaDOS tracks can be written to ADF, thus forcing me to write to IPF (or HFE) or whatever else nonstandard.

**Comment by keirf** [comment]
You can't write longtracks to ADF. My workflow for new titles is where possible to create an ADF (which will fail protection checks if any). I then run in UAE with trapping on disk access to the protection track. When that triggers, from the UAE debug monitor I dump and disassemble the protection routine (which is usually fully decrypted at that point) and have a look.

Just because some versions of a game have protection, doesn't mean all do. Like I say, I can see protection on the IPF of KQ3, but not your dump. And there really is no protection at all on KQ2, your dump or the IPF -- but doesn't mean there aren't versions which do!

Anyway, because I boldly claim your KQ2 and KQ3 have no protections, you can convert them to ADF just fine, and fix up the bootblock:
```
disk-analyse RAW/KingsQuestIII kq3.adf
adfbb kq3.adf -w
```

**Comment by keirf** [comment]
And then when you get dumped at the CLI, the command to run is iirc one of `KQ2` or `KQ3` or `Sierra`.

**Comment by KKR775** [comment]
thanks Keir, I have been quite busy these past few weeks, but yes as far as I am concerned this case is closed. I will let you know if any issue arises. Seasons Greetings !
