### ISSUE TITLE
Disk-analyse option for RAW sector data conversions

### ISSUE THREAD

**Issue by staticmem** [keirf/Disk-Utilities#71]
I tried your disk-analyse utility and had success with conversion of CP/M MFM SCP image to IMD (ImageDisk) format.  I had partial success with the Atari ST format but does not do 10 s/t as normally ST is only 9 s/t but the resultant image is in a RAW format that I would like to be able to have.

Can you add a general RAW sector data output file format for MFM/FM CP/M disks and provide options to specify the number of sectors per track and size of the sectors? For ordinary RAW disk images static values would suffice for the entire disk.  I see you can already specify SS disk and start/end cylinders so would be good to have these other options.

The DSK (LibDisk) file format did not work and quite small file output file.  Is this the same as the CPCEMU DSK image format or some other format?

**Comment by staticmem** [comment]
I had a look around and found in "ibm_img.c" the ST handler and changed the value of number of sectors to 10 instead of 9.

This seems to work fine and resulted in a 819200 byte disk image (80x2x512x10) but needs to be done correctly but at this stage I don't know what needs to done exactly including adding the 2 options I mention previously.

I can probably submit something if I knew what I need to do exactly or would you prefer to do this?

```
struct track_handler atari_st_handler = {
    .density = trkden_double,
    .bytes_per_sector = 512,
//    .nr_sectors = 9,
// quick hack for 10 s/t disks
    .nr_sectors = 10,
    .write_raw = ibm_img_write_raw,
    .read_raw = ibm_img_read_raw,
    .write_sectors = ibm_img_write_sectors,
    .read_sectors = ibm_img_read_sectors,
    .extra_data = & (struct ibm_extra_data) {
        .sector_base = 1
    }
};

```

**Comment by keirf** [comment]
Try `--format=ibm_mfm_dd`

**Comment by staticmem** [comment]
That worked and also allowed me to have a sector base higher than 1. Thanks.

Can you elaborate on the DSK image file type and whether it is the same as that defined for CPCEMU DSK images?

**Comment by staticmem** [comment]
From what I could find on the Internet the DSK images appear to be Apple Macintosh floppy disk images.

**Comment by keirf** [comment]
The DSK is my own format I did for disk-analyse. It's not really super useful to anyone to be honest. I should get rid or at least use a less overloaded file extension for it :)

Sadly disk-analyse does not currently support CPCEMU DSK.

**Comment by d235j** [comment]
What would be useful is a "resolved" version of SCP (or similar flux type image) — one that resolves a multitrack raw dump into a "canonical" single-track dump.

This way we wouldn't have to do processing/resolution in MAME. This would be similar (in a sense) to the [Applesauce WOZ format](https://applesaucefdc.com/woz/).

**Comment by keirf** [comment]
That is exactly what disk-analyse is producing, when it produces SCP output. It is supposed to do full track analysis and regenerate the flux perfectly, single rev.

**Comment by staticmem** [comment]
> Sadly disk-analyse does not currently support CPCEMU DSK.

I wrote a shell script that reads the disk then uses Disk Analyse (DA) and one of my own converters that supports CPCEMU DSK disk images.  By default if I ask for a DSK image to be created DA is used to first convert to an IBM MFM raw image than I feed that into my converter.

For your DSK image if I request an ADSK image it will use DA to create it.  I also have options to force one converter over the other.  If I use my converter it adds another precess but it's all very quick and uses a temporary directory and copies back the completed disk image.

From my side of it while having exact images is good I want to feed these back into emulators.

I would like to see the gw.py script be able to act like a real-time track buffer where a single track on side 0 or 1 can be read and written, then access the required sector after it has been converted then write the track back as an SCP image even if it means only one byte in a sector changed.
