### ISSUE TITLE
Cross compiling on Linux for win32 binaries

### ISSUE THREAD

**Issue by staticmem** [keirf/Disk-Utilities#72]
I made some changes in Rules.mk so that I could cross compile but I'm not getting to far.  I installed the header files for Caps.  I don't want to make changes but need a Windows binary but can't find any.

Here is some of the output...
caps=y make

......
make[2]: Entering directory '/home/staticmem/Builds_mingw32/Disk-Utilities-master/libdisk/container'
i686-w64-mingw32-gcc -O2 -fno-strict-aliasing -std=gnu99 -Wall -Werror -I../../libdisk/include -MMD -MF ./.dsk.opic.d  -fPIC -fvisibility=hidden -c -o dsk.opic dsk.c
In file included from dsk.c:16:0:
/usr/share/mingw-w64/include/time.h:278:34: error: expected identifier or ‘(’ before ‘struct’

Line 278 has...
#ifdef _POSIX_THREAD_SAFE_FUNCTIONS
__forceinline struct tm *__cdecl localtime_r(const time_t *_Time, struct tm *_Tm) {
  return localtime_s(_Tm, _Time) ? NULL : _Tm;

Is this a POSIX issue?  and Is the only way to build this by using CYGWIN?

**Comment by keirf** [comment]
It's built on MinGW before but it's probably rotted and also not kept up with latest MinGW.

The error above looks like it could be barfing on `__forceinline`. Perhaps that isn't defined yet? Perhaps you need to include some other header?

**Comment by tomse** [comment]
A little off topic but it may help you. Win10 has an excellent Linux Subsystem, if you install the subsystem feature, and go to MS Store, you can download i.e. Ubuntu. 
Once installed you have access to all your local drives from the Linux shell (/mnt/) and can work perfectly with the disk-utilities.

**Comment by staticmem** [comment]
Thanks tomse, I am aware of W10 has support for linux but I develop/build under Linux.  I do have a have W7 installed under Virtual box but that is too early a version so can't be used and used mainly for testing.

**Comment by keirf** [comment]
I may remove mingw support altogether, as it isn't actually supported by me and no one else maintains it.

**Comment by d235j** [comment]
Builds fine for me and runs (to generate the help screen) on 64-bit MinGW with no Makefile changes.
If I override the ARCH in rules.mk to force a 32-bit build, it also builds fine for me and runs.

I suspect a problem in @staticmem's MSYS environment.

**Comment by tomse** [comment]
@staticmem I can recommend that you get win10, win7 will be end of life very soon. and you can get a trial win10 that doesn't expire (though some features/cosmetics will be disabled - background pic etc).   

I do understand that 32bit and older versions may be needed on some setups

**Comment by staticmem** [comment]
@d235j As I use Linux for devlopment I have no MSYS.  Under W7 I do use the "Gow" suite which allows Unices like commands and a bash environment for testing scripts I supply to others Windows users so that I don't have to rewrite as BAT files. (Maybe I should learn Python or Perl).

Part of the problems is that Rules.mk needs to be fixed to be able to cross compile.  Also the Makefile needs to add an ".ext" to the created binaries which needs defining in the Rules.mk.

The " __forceinline" directive as Keirf has pointed out appears to be the main problem right now stopping  cross compiling succeeding.  I'm running a fully up to date Linux Mint 19 Tara.

**Comment by keirf** [comment]
Okay I'm not sure what can be done here. Cross compilation is not supported unless some developer does the work to make it build. It sounds like mingw builds work (on Windows proper). So really this whole report is a notbug and a wontfix, right?

**Comment by staticmem** [comment]
I'm not saying it's a bug per say, maybe I should have stated "Rules.mk needs to be modified" for cross building.  I noticed there is a "winegcc" maybe that can be used but found it difficult understand how to use it.
