### ISSUE TITLE
tracks are damaged or unidentified

### ISSUE THREAD

**Issue by mrdavoudi1** [keirf/Disk-Utilities#75]
Thanks  you for your amazing software and hardware FF and GW and disk-analyse
I read a 1.44 MB disk with my ordinary IBM 1.44mb 3.5 FDD with GREASEWEAZLE.
I write the SCP file healthy to another diskette with GW.py .
the scp file is open and export normally in HXC software and exported image work well.
but with  disk-analyse  when i want to export .img or .hfe  report me some track are damaged or unidentified.
what's the problem?
what's the solution? 

![s](https://user-images.githubusercontent.com/50794195/77306659-a0ef4e80-6d15-11ea-86e6-ad073d6d7ed3.jpg)
![max](https://user-images.githubusercontent.com/50794195/77306664-a351a880-6d15-11ea-96f4-010e1548370d.jpg)
![maxhxc](https://user-images.githubusercontent.com/50794195/77306667-a482d580-6d15-11ea-8d43-822c94aeda76.jpg)
![scp-disk view](https://user-images.githubusercontent.com/50794195/77313360-5a075600-6d21-11ea-8259-a5ec29d214a6.jpg)

**Comment by keirf** [comment]
Command line should be:
```disk-analyse --format=ibm_mfm_hd s.scp sdskimg.img```
