### ISSUE TITLE
atari_st image format needs to be expanded: Error with .scp file

### ISSUE THREAD

**Issue by M1kerochip** [keirf/Disk-Utilities#81]
Hi, the file: https://archive.org/download/ST_Action_UK_Magazine_Coverdisk_Disk_Image/STAction_Issue35_1991-03_InteractivePublishing_Disk15of58_AtariST_Dump.7z

can't be converted to a .ipf using either atari_st or ibm_mfm_dd
Most of the other disks in that archive fail too, with -f atari_st but are fine with the ibm_mfm_dd

Many (most?) people used disk formatting programs to create 10 sector 84 track disks, and in some cases 11 sector ones too.
Those are all magazine cover disks in the archive, and bar a small few, they're 10 sector disks.

Can you expand the atari_st format to include searching for 10 and 11 sector disks, like the IBM one?

**Comment by keirf** [comment]
Atari ST format is basically IBM format. And the `ibm_mfm_dd` format handler is better than the one used for `atari_st`. So actually I would recommend to continue using `ibm_mfm_dd` but keep an eye that the expected number of sectors is seen on every track (bad sectors are silently dropped currently, but you will such tracks having too few sectors in the final report).

I have just fixed `ibm_mfm_dd` to handle the supplied STAction image.

**Comment by keirf** [comment]
I have also changed `atari_st` to mean exactly the same as `ibm_mfm_dd`.
