### ISSUE TITLE
Ignoring index sensor in scp_dump

### ISSUE THREAD

**Issue by dmatech1** [keirf/Disk-Utilities#82]
Is there some way in `scp_dump` to ignore the index sensor?  According to [this post](https://www.cbmstuff.com/forum/showthread.php?tid=766&pid=5001#pid5001) in the official SCP forums, that's now an accepted way of reading the back side of these diskettes that used both sides separately.  When I do this, I get the following error:

```
Supercard Pro: Hardware v1.1; Firmware v1.2
Reading track 0   ...scp_dump: Command a0 (Read Flux) failed: 09 (NoIndex)
```

**Comment by keirf** [comment]
I don't believe it is clearly documented how to do an index-less read. The read length is specified to the Supercard Pro firmware as a number of revolutions (index pulses).
