### ISSUE TITLE
HFE->IPF conversion doesn't seem to transfer raw contents of tracks

### ISSUE THREAD

**Issue by mankeli** [keirf/Disk-Utilities#85]
I'm generating a HFE image for my program and trying to convert it to IPF with disk-utility.

First track is standard amigados track. On second track there's a custom syncword and some other words of test data there. On real amiga (with flashfloppy) the HFE image works and syncword is found. (should be the turquise rasterbar) On emulator (with the converted IPF) the DMA never begins. (indicated by fullscreen green color)

I'm looking at the IPF file and there's nothing on the second track.
http://lerppu.net/markus68k-secret/writer2.hfe
http://lerppu.net/markus68k-secret/writer2.ipf

**Comment by keirf** [comment]
What was the command line to convert it? And the text output? disk-analyse needs to be taught about new track formats (usually).

**Comment by mankeli** [comment]
```
$ ~/src/Disk-Utilities/disk-analyse/disk-analyse writer2.hfe writer2.ipf
T0.0: AmigaDOS
T0.1-79.1: Unformatted*
T80.0-83.1: Unformatted
** WARNING: 159 tracks are damaged or unidentified!

```

**Comment by keirf** [comment]
Yes you need a new format specified in the formats file, it should specify amigados for track 0 and raw_dd for the rest.

**Comment by mankeli** [comment]
Thank you for help! adding -f raw_dd makes an .ipf that works on emu too.
