### ISSUE TITLE
First release?

### ISSUE THREAD

**Issue by kloczek** [keirf/Disk-Utilities#87]
Is irt possible to make first release and tag it in repo?

**Comment by keirf** [comment]
I've never thought much about releases on this repository. I don't gather features, or stabilise, or anything. It just rolls along.

**Comment by kloczek** [comment]
Issue is that on packaging any software you need to assign exact version.
New (increased) version of any software needs to be assigned on new release as well.

If exact software has not (yet) version it is kind impossible to package it :)
In other words it is not about releasing something as stable or gathering features. It is about marking some points where software is ready to use (because beteen those points what is commited in single commit may not be finished as whole change to the point where something is ready to compile and use).
Tagging git repo spreads as well some signals to people who are watching github/gitlab repository.

For the packaging there are some rules about version string. It should consist auto of numbers and those numbers may have some sections separated by (only) dots. Please don't use underscores or dashes as those characters cannot be as string by any packaging software.
Easies convention for rolling along versions is for example use date in forma `<year>.<month>.<day>` or `<year><month><day>`

**Comment by keirf** [comment]
Okay, I made a tag. Is that all you need?

**Comment by kloczek** [comment]
Yep :)

Thak you. Closing ticket.
