### ISSUE TITLE
Converting SCP to EADF works less accurately than FS-UAE.

### ISSUE THREAD

**Issue by DagAgren** [keirf/Disk-Utilities#89]
I haven't looked closely into what is going on here, but I just got a Greaseweazle F1 and was testing it on some really old disks formatted using Diskspare.device on the Amiga (so 82 tracks in custom format).

I can convert them to EADF using raw_dd format since disk-analyse does not seem to support the Diskspare.device format, but the resulting images had a lot of read errors when accessed from FS-UAE.

If I just feed the SCP files directly to FS-UAE, I still get a few read errors but a lot less. Is some part of the decoding of the flux less accurate in disk-analyse than in FS-UAE?

**Comment by keirf** [comment]
Conversion is a single revolution index-to-index. AmigaDOS disks are often not index aligned and have sectors straddling the index mark. Such sectors will be corrupted by the conversion. However, such disks are usually pure AmigaDOS and can be converted using `--format=amigados`.
