### ISSUE TITLE
Incorrect checksum from scp file dumped with adf-copy

### ISSUE THREAD

**Issue by tomse** [keirf/Disk-Utilities#92]
Trying to convert SCP files that has been dumped with ADF-Copy gives a bad checksum

```
/mnt/g$ disk-analyse copy_disk_15.scp copy_disk_15.adf
disk-analyse: copy_disk_15.scp has bad checksum
```
using the HxC tools doesn't mention bad checksum

I can't say if it's a "feature" in disk-analyze or if it's ADF-Copy 
(adf-copy uses a teensy 3.2 to dump disks / similar to greaseweazel)

Attached is a scp dump, created by adf-copy

[copy_disk_15.zip](https://github.com/keirf/Disk-Utilities/files/7144333/copy_disk_15.zip)

**Comment by keirf** [comment]
This is ADF-Copy bug possibly, but since it leaves the checksum field as 0, let's use that as an indication to skip the checksum.
