### ISSUE TITLE
RX02 support broke in c0dafed

### ISSUE THREAD

**Issue by wohali** [keirf/disk-utilities#95]
Building off of HEAD with a known "mostly OK" RX02 floppy rip:

```
$ ./disk-analyse --format=DEC-RX02  --rpm=360 ~/Wakko/foo_2.scp foo.img
T0.0-79.1: Unformatted*
T80.0-83.1: Unformatted
```

I am able to bisect the failure back to c0dafed, which adds the `--double-step` option. Its parent 86fbfdf still works fine. Specifying `--double-step` does not restore RX02 analysis functionality.

**Comment by keirf** [comment]
Can you zip and attach the scp?

**Comment by wohali** [comment]
Sure, here's one.
[rt11v4-d2.zip](https://github.com/keirf/disk-utilities/files/8039111/rt11v4-d2.zip)

**Comment by keirf** [comment]
Building off HEAD (`ab0e448e`):
```
$ ./disk-analyse/disk-analyse --rpm=360 --format=DEC-RX02 -S -e 76 ./rt11v4-d2.scp a.img
T0.0-76.0: DEC-RX02 8in (26 256-byte sectors, 6656 bytes)
```

**Comment by wohali** [comment]
I can reproduce the failure at will as stated in my first post. Build log attached, including the unsuccessful c0dafed checkout and the successful 86fbfdf build. Each time I am running `make clean && make` before continuing.

[broken.txt](https://github.com/keirf/disk-utilities/files/8044005/broken.txt)

If it's not the code, what am I doing wrong?

**Comment by wohali** [comment]
Note that the test machine is running Debian `bullseye`. I can test older releases (e.g. `buster`) or various Ubuntus, CentOS, etc. if you suspect a system library.

**Comment by wohali** [comment]
OK, the issue is on my end and seems to have been an invalid `libdisk` on the standard path.

I can get HEAD running correctly if I:

```
$ LD_LIBRARY_PATH=../libdisk ./disk-analyse --rpm=360 --format=DEC-RX02 -S -e 76 ./rt11v4-d2.scp a.img
T0.0-76.0: DEC-RX02 8in (26 256-byte sectors, 6656 bytes)
```

Sorry for the bad bug report.
